// Abilities and spells for Lateania.
//
// Every class skill and spell is one `Ability` record: pure data, the same shape
// a future content file would hold. Abilities unlock by level (see classes.rs),
// cost the class resource, and apply one effect when used. Spells, skills,
// poisons, and buffs are unified under `AbilityEffect` so the combat runtime
// needs only one resolution path - the highest-leverage design choice in the
// engine.

use super::classes::{Class, Resource};
use super::damage::DamageType;

/// What an ability does when it lands. Instant effects apply once; the timed
/// variants seed an ongoing effect resolved on each world tick.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AbilityEffect {
    /// Immediate damage to the current target.
    Strike,
    /// Damage now, then more each tick for `duration` ticks (bleeds, poisons, burns).
    DamageOverTime,
    /// Restore the caster's health immediately.
    Heal,
    /// Restore health now and each tick for `duration` ticks.
    HealOverTime,
    /// Temporary bonus to outgoing damage for `duration` ticks.
    Empower,
    /// Temporary damage-absorbing shield for `duration` ticks.
    Ward,
    /// Skip the target's next attack (a stun / disable).
    Stun,
    /// Heavy single hit that also briefly empowers the caster (execute-style).
    Finisher,
}

impl AbilityEffect {
    pub fn label(self) -> &'static str {
        match self {
            Self::Strike => "damage",
            Self::DamageOverTime => "damage over time",
            Self::Heal => "heal",
            Self::HealOverTime => "heal over time",
            Self::Empower => "empower",
            Self::Ward => "shield",
            Self::Stun => "stun",
            Self::Finisher => "finisher",
        }
    }
}

/// A single learnable ability or spell.
#[derive(Clone, Copy, Debug)]
pub struct Ability {
    pub id: u32,
    pub name: &'static str,
    pub desc: &'static str,
    pub class: Class,
    /// Character level at which this unlocks.
    pub level_req: i32,
    /// Resource spent to use it.
    pub cost: i32,
    pub resource: Resource,
    /// World ticks before it can be used again.
    pub cooldown_ticks: u32,
    pub effect: AbilityEffect,
    /// Damage school for offensive abilities (ignored by heals/buffs/wards).
    pub damage_type: DamageType,
    /// Base magnitude (damage, heal, shield, or bonus depending on effect).
    pub magnitude: i32,
    /// Ticks an over-time or buff effect persists (0 for instant effects).
    pub duration: u8,
}

/// The full ability roster. Ordered by class, then unlock level.
pub const ABILITIES: &[Ability] = &[
    // ---- Warrior (Rage) -------------------------------------------------
    Ability {
        id: 100,
        name: "Cleave",
        desc: "A wide, brutal swing that bites deep into the enemy before you.",
        class: Class::Warrior,
        level_req: 1,
        cost: 10,
        resource: Resource::Rage,
        cooldown_ticks: 1,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Physical,
        magnitude: 14,
        duration: 0,
    },
    Ability {
        id: 101,
        name: "Rend",
        desc: "Tear a ragged wound that bleeds the foe with every passing moment.",
        class: Class::Warrior,
        level_req: 4,
        cost: 12,
        resource: Resource::Rage,
        cooldown_ticks: 2,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Physical,
        magnitude: 6,
        duration: 4,
    },
    Ability {
        id: 102,
        name: "Shield Wall",
        desc: "Set your stance and raise your guard, turning aside the next blows.",
        class: Class::Warrior,
        level_req: 8,
        cost: 15,
        resource: Resource::Rage,
        cooldown_ticks: 6,
        effect: AbilityEffect::Ward,
        damage_type: DamageType::Physical,
        magnitude: 30,
        duration: 3,
    },
    Ability {
        id: 103,
        name: "Shield Bash",
        desc: "Slam your shield into the enemy's skull, stunning it senseless.",
        class: Class::Warrior,
        level_req: 12,
        cost: 18,
        resource: Resource::Rage,
        cooldown_ticks: 5,
        effect: AbilityEffect::Stun,
        damage_type: DamageType::Physical,
        magnitude: 10,
        duration: 1,
    },
    Ability {
        id: 104,
        name: "Battle Fury",
        desc: "Loose a war-cry that floods your arms with killing strength.",
        class: Class::Warrior,
        level_req: 16,
        cost: 20,
        resource: Resource::Rage,
        cooldown_ticks: 8,
        effect: AbilityEffect::Empower,
        damage_type: DamageType::Physical,
        magnitude: 10,
        duration: 4,
    },
    Ability {
        id: 105,
        name: "Sunder",
        desc: "A crushing two-handed blow that shatters armor and bone alike.",
        class: Class::Warrior,
        level_req: 20,
        cost: 22,
        resource: Resource::Rage,
        cooldown_ticks: 3,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Physical,
        magnitude: 30,
        duration: 0,
    },
    Ability {
        id: 106,
        name: "Bloodthirst",
        desc: "Strike with such savagery that the enemy's blood revives you.",
        class: Class::Warrior,
        level_req: 25,
        cost: 24,
        resource: Resource::Rage,
        cooldown_ticks: 4,
        effect: AbilityEffect::Heal,
        damage_type: DamageType::Physical,
        magnitude: 28,
        duration: 0,
    },
    Ability {
        id: 107,
        name: "Earthshaker",
        desc: "Drive your weapon into the ground; the shock rends everything near.",
        class: Class::Warrior,
        level_req: 30,
        cost: 28,
        resource: Resource::Rage,
        cooldown_ticks: 4,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Physical,
        magnitude: 12,
        duration: 5,
    },
    Ability {
        id: 108,
        name: "Indomitable",
        desc: "Plant your feet and refuse to fall, shrugging off mortal wounds.",
        class: Class::Warrior,
        level_req: 36,
        cost: 30,
        resource: Resource::Rage,
        cooldown_ticks: 10,
        effect: AbilityEffect::Ward,
        damage_type: DamageType::Physical,
        magnitude: 70,
        duration: 4,
    },
    Ability {
        id: 109,
        name: "Reckless Onslaught",
        desc: "Abandon all defense for a flurry of devastating, empowered blows.",
        class: Class::Warrior,
        level_req: 42,
        cost: 35,
        resource: Resource::Rage,
        cooldown_ticks: 10,
        effect: AbilityEffect::Empower,
        damage_type: DamageType::Physical,
        magnitude: 22,
        duration: 5,
    },
    Ability {
        id: 110,
        name: "Executioner's Strike",
        desc: "A single annihilating blow meant to end the fight outright.",
        class: Class::Warrior,
        level_req: 50,
        cost: 45,
        resource: Resource::Rage,
        cooldown_ticks: 8,
        effect: AbilityEffect::Finisher,
        damage_type: DamageType::Physical,
        magnitude: 80,
        duration: 2,
    },
    // ---- Mage (Mana) ----------------------------------------------------
    Ability {
        id: 200,
        name: "Firebolt",
        desc: "A dart of conjured flame that sears whatever it strikes.",
        class: Class::Mage,
        level_req: 1,
        cost: 8,
        resource: Resource::Mana,
        cooldown_ticks: 1,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Fire,
        magnitude: 16,
        duration: 0,
    },
    Ability {
        id: 201,
        name: "Frost Nova",
        desc: "Ice erupts around the foe, locking it in place for a heartbeat.",
        class: Class::Mage,
        level_req: 5,
        cost: 14,
        resource: Resource::Mana,
        cooldown_ticks: 5,
        effect: AbilityEffect::Stun,
        damage_type: DamageType::Frost,
        magnitude: 8,
        duration: 1,
    },
    Ability {
        id: 202,
        name: "Immolate",
        desc: "Wreath the enemy in clinging fire that burns long after the cast.",
        class: Class::Mage,
        level_req: 9,
        cost: 16,
        resource: Resource::Mana,
        cooldown_ticks: 3,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Fire,
        magnitude: 9,
        duration: 5,
    },
    Ability {
        id: 203,
        name: "Mana Shield",
        desc: "Weave raw arcana into a shimmering barrier of force.",
        class: Class::Mage,
        level_req: 13,
        cost: 18,
        resource: Resource::Mana,
        cooldown_ticks: 6,
        effect: AbilityEffect::Ward,
        damage_type: DamageType::Arcane,
        magnitude: 35,
        duration: 3,
    },
    Ability {
        id: 204,
        name: "Arcane Focus",
        desc: "Sharpen your will until every spell strikes with greater force.",
        class: Class::Mage,
        level_req: 17,
        cost: 20,
        resource: Resource::Mana,
        cooldown_ticks: 8,
        effect: AbilityEffect::Empower,
        damage_type: DamageType::Arcane,
        magnitude: 12,
        duration: 4,
    },
    Ability {
        id: 205,
        name: "Lightning Lance",
        desc: "A spear of white lightning that punches clean through the target.",
        class: Class::Mage,
        level_req: 22,
        cost: 24,
        resource: Resource::Mana,
        cooldown_ticks: 2,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Lightning,
        magnitude: 34,
        duration: 0,
    },
    Ability {
        id: 206,
        name: "Siphon Life",
        desc: "Draw the warmth from the enemy and pour it into your own flesh.",
        class: Class::Mage,
        level_req: 27,
        cost: 26,
        resource: Resource::Mana,
        cooldown_ticks: 4,
        effect: AbilityEffect::Heal,
        damage_type: DamageType::Shadow,
        magnitude: 30,
        duration: 0,
    },
    Ability {
        id: 207,
        name: "Blizzard",
        desc: "Call down a storm of razored ice that flays all it touches.",
        class: Class::Mage,
        level_req: 32,
        cost: 30,
        resource: Resource::Mana,
        cooldown_ticks: 4,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Frost,
        magnitude: 13,
        duration: 5,
    },
    Ability {
        id: 208,
        name: "Time Warp",
        desc: "Bend the moment so the enemy stands frozen between heartbeats.",
        class: Class::Mage,
        level_req: 38,
        cost: 34,
        resource: Resource::Mana,
        cooldown_ticks: 9,
        effect: AbilityEffect::Stun,
        damage_type: DamageType::Arcane,
        magnitude: 14,
        duration: 2,
    },
    Ability {
        id: 209,
        name: "Arcane Overload",
        desc: "Let power flood every nerve until your spells blaze unstoppable.",
        class: Class::Mage,
        level_req: 44,
        cost: 38,
        resource: Resource::Mana,
        cooldown_ticks: 10,
        effect: AbilityEffect::Empower,
        damage_type: DamageType::Arcane,
        magnitude: 24,
        duration: 5,
    },
    Ability {
        id: 210,
        name: "Meteor",
        desc: "Tear a burning star from the sky and bring it down on your foe.",
        class: Class::Mage,
        level_req: 50,
        cost: 50,
        resource: Resource::Mana,
        cooldown_ticks: 8,
        effect: AbilityEffect::Finisher,
        damage_type: DamageType::Fire,
        magnitude: 90,
        duration: 2,
    },
    // ---- Cleric (Mana) --------------------------------------------------
    Ability {
        id: 300,
        name: "Smite",
        desc: "Call down a lance of holy light upon the unworthy.",
        class: Class::Cleric,
        level_req: 1,
        cost: 9,
        resource: Resource::Mana,
        cooldown_ticks: 1,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Holy,
        magnitude: 13,
        duration: 0,
    },
    Ability {
        id: 301,
        name: "Mend",
        desc: "Knit flesh and seal wounds with a whispered prayer.",
        class: Class::Cleric,
        level_req: 3,
        cost: 12,
        resource: Resource::Mana,
        cooldown_ticks: 2,
        effect: AbilityEffect::Heal,
        damage_type: DamageType::Holy,
        magnitude: 22,
        duration: 0,
    },
    Ability {
        id: 302,
        name: "Renewal",
        desc: "A blessing that mends a little more with every breath you take.",
        class: Class::Cleric,
        level_req: 7,
        cost: 16,
        resource: Resource::Mana,
        cooldown_ticks: 4,
        effect: AbilityEffect::HealOverTime,
        damage_type: DamageType::Holy,
        magnitude: 8,
        duration: 5,
    },
    Ability {
        id: 303,
        name: "Sacred Ward",
        desc: "Surround yourself in a corona of divine protection.",
        class: Class::Cleric,
        level_req: 11,
        cost: 18,
        resource: Resource::Mana,
        cooldown_ticks: 6,
        effect: AbilityEffect::Ward,
        damage_type: DamageType::Holy,
        magnitude: 32,
        duration: 3,
    },
    Ability {
        id: 304,
        name: "Holy Fire",
        desc: "Sear the wicked with flame that judges as it burns.",
        class: Class::Cleric,
        level_req: 15,
        cost: 20,
        resource: Resource::Mana,
        cooldown_ticks: 3,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Holy,
        magnitude: 10,
        duration: 4,
    },
    Ability {
        id: 305,
        name: "Blessing of Might",
        desc: "Anoint yourself so each strike falls with righteous force.",
        class: Class::Cleric,
        level_req: 19,
        cost: 22,
        resource: Resource::Mana,
        cooldown_ticks: 8,
        effect: AbilityEffect::Empower,
        damage_type: DamageType::Holy,
        magnitude: 11,
        duration: 4,
    },
    Ability {
        id: 306,
        name: "Greater Heal",
        desc: "A surge of restoring grace that mends even grievous harm.",
        class: Class::Cleric,
        level_req: 24,
        cost: 26,
        resource: Resource::Mana,
        cooldown_ticks: 3,
        effect: AbilityEffect::Heal,
        damage_type: DamageType::Holy,
        magnitude: 50,
        duration: 0,
    },
    Ability {
        id: 307,
        name: "Hammer of Faith",
        desc: "A spectral warhammer crashes down with crushing zeal.",
        class: Class::Cleric,
        level_req: 29,
        cost: 28,
        resource: Resource::Mana,
        cooldown_ticks: 3,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Holy,
        magnitude: 32,
        duration: 0,
    },
    Ability {
        id: 308,
        name: "Sanctuary",
        desc: "Raise hallowed ground that turns aside the cruelest wounds.",
        class: Class::Cleric,
        level_req: 35,
        cost: 32,
        resource: Resource::Mana,
        cooldown_ticks: 9,
        effect: AbilityEffect::Ward,
        damage_type: DamageType::Holy,
        magnitude: 65,
        duration: 4,
    },
    Ability {
        id: 309,
        name: "Divine Radiance",
        desc: "Blaze with the light of the Dawn until evil cannot bear to strike.",
        class: Class::Cleric,
        level_req: 41,
        cost: 36,
        resource: Resource::Mana,
        cooldown_ticks: 7,
        effect: AbilityEffect::Stun,
        damage_type: DamageType::Holy,
        magnitude: 18,
        duration: 2,
    },
    Ability {
        id: 310,
        name: "Judgment",
        desc: "Pronounce the final verdict of heaven upon a doomed soul.",
        class: Class::Cleric,
        level_req: 50,
        cost: 48,
        resource: Resource::Mana,
        cooldown_ticks: 8,
        effect: AbilityEffect::Finisher,
        damage_type: DamageType::Holy,
        magnitude: 78,
        duration: 2,
    },
    // ---- Rogue (Energy) -------------------------------------------------
    Ability {
        id: 400,
        name: "Backstab",
        desc: "Slip a blade between the ribs where it does the most harm.",
        class: Class::Rogue,
        level_req: 1,
        cost: 8,
        resource: Resource::Energy,
        cooldown_ticks: 1,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Physical,
        magnitude: 18,
        duration: 0,
    },
    Ability {
        id: 401,
        name: "Envenom",
        desc: "Coat your blade so each cut festers with creeping poison.",
        class: Class::Rogue,
        level_req: 4,
        cost: 10,
        resource: Resource::Energy,
        cooldown_ticks: 2,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Poison,
        magnitude: 7,
        duration: 5,
    },
    Ability {
        id: 402,
        name: "Blind",
        desc: "Fling grit and powder to leave your foe swinging at shadows.",
        class: Class::Rogue,
        level_req: 8,
        cost: 12,
        resource: Resource::Energy,
        cooldown_ticks: 5,
        effect: AbilityEffect::Stun,
        damage_type: DamageType::Physical,
        magnitude: 8,
        duration: 1,
    },
    Ability {
        id: 403,
        name: "Evasion",
        desc: "Move like smoke, slipping every blow aimed your way.",
        class: Class::Rogue,
        level_req: 12,
        cost: 14,
        resource: Resource::Energy,
        cooldown_ticks: 7,
        effect: AbilityEffect::Ward,
        damage_type: DamageType::Physical,
        magnitude: 28,
        duration: 3,
    },
    Ability {
        id: 404,
        name: "Cold Blood",
        desc: "Steady your hand and your heart for one perfect, lethal cut.",
        class: Class::Rogue,
        level_req: 16,
        cost: 16,
        resource: Resource::Energy,
        cooldown_ticks: 8,
        effect: AbilityEffect::Empower,
        damage_type: DamageType::Physical,
        magnitude: 14,
        duration: 3,
    },
    Ability {
        id: 405,
        name: "Eviscerate",
        desc: "A flurry of blades that opens the enemy from hip to throat.",
        class: Class::Rogue,
        level_req: 21,
        cost: 20,
        resource: Resource::Energy,
        cooldown_ticks: 2,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Physical,
        magnitude: 32,
        duration: 0,
    },
    Ability {
        id: 406,
        name: "Crippling Toxin",
        desc: "A paralytic venom that seizes the muscles and stops the breath.",
        class: Class::Rogue,
        level_req: 26,
        cost: 22,
        resource: Resource::Energy,
        cooldown_ticks: 6,
        effect: AbilityEffect::Stun,
        damage_type: DamageType::Poison,
        magnitude: 12,
        duration: 2,
    },
    Ability {
        id: 407,
        name: "Hemorrhage",
        desc: "Strike a vein that will not close, bleeding the foe dry.",
        class: Class::Rogue,
        level_req: 31,
        cost: 24,
        resource: Resource::Energy,
        cooldown_ticks: 4,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Physical,
        magnitude: 14,
        duration: 5,
    },
    Ability {
        id: 408,
        name: "Shadowstep",
        desc: "Vanish into shadow and return where no blade can find you.",
        class: Class::Rogue,
        level_req: 37,
        cost: 28,
        resource: Resource::Energy,
        cooldown_ticks: 9,
        effect: AbilityEffect::Ward,
        damage_type: DamageType::Shadow,
        magnitude: 60,
        duration: 4,
    },
    Ability {
        id: 409,
        name: "Killing Spree",
        desc: "Become a whirlwind of steel, every cut emptier and crueler.",
        class: Class::Rogue,
        level_req: 43,
        cost: 32,
        resource: Resource::Energy,
        cooldown_ticks: 10,
        effect: AbilityEffect::Empower,
        damage_type: DamageType::Physical,
        magnitude: 26,
        duration: 5,
    },
    Ability {
        id: 410,
        name: "Assassinate",
        desc: "The single strike every rogue trains a lifetime to land.",
        class: Class::Rogue,
        level_req: 50,
        cost: 42,
        resource: Resource::Energy,
        cooldown_ticks: 8,
        effect: AbilityEffect::Finisher,
        damage_type: DamageType::Physical,
        magnitude: 88,
        duration: 2,
    },
    // ---- Ranger (Focus) -------------------------------------------------
    Ability {
        id: 500,
        name: "Aimed Shot",
        desc: "Draw, breathe, and loose an arrow exactly where it will hurt.",
        class: Class::Ranger,
        level_req: 1,
        cost: 8,
        resource: Resource::Focus,
        cooldown_ticks: 1,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Physical,
        magnitude: 15,
        duration: 0,
    },
    Ability {
        id: 501,
        name: "Serpent Sting",
        desc: "An arrow tipped in adder-venom that sickens with every beat.",
        class: Class::Ranger,
        level_req: 4,
        cost: 11,
        resource: Resource::Focus,
        cooldown_ticks: 2,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Poison,
        magnitude: 7,
        duration: 5,
    },
    Ability {
        id: 502,
        name: "Snare Trap",
        desc: "Set a hidden snare that seizes the foe fast in its teeth.",
        class: Class::Ranger,
        level_req: 8,
        cost: 13,
        resource: Resource::Focus,
        cooldown_ticks: 5,
        effect: AbilityEffect::Stun,
        damage_type: DamageType::Physical,
        magnitude: 9,
        duration: 1,
    },
    Ability {
        id: 503,
        name: "Mark of the Hunt",
        desc: "Read your quarry's weakness and let every shot find it.",
        class: Class::Ranger,
        level_req: 12,
        cost: 15,
        resource: Resource::Focus,
        cooldown_ticks: 8,
        effect: AbilityEffect::Empower,
        damage_type: DamageType::Physical,
        magnitude: 10,
        duration: 4,
    },
    Ability {
        id: 504,
        name: "Mend Companion",
        desc: "Tend your own hurts with the field-craft of a thousand camps.",
        class: Class::Ranger,
        level_req: 16,
        cost: 17,
        resource: Resource::Focus,
        cooldown_ticks: 4,
        effect: AbilityEffect::HealOverTime,
        damage_type: DamageType::Physical,
        magnitude: 9,
        duration: 5,
    },
    Ability {
        id: 505,
        name: "Piercing Arrow",
        desc: "A shot loosed with such force it drives clean through plate.",
        class: Class::Ranger,
        level_req: 21,
        cost: 20,
        resource: Resource::Focus,
        cooldown_ticks: 2,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Physical,
        magnitude: 33,
        duration: 0,
    },
    Ability {
        id: 506,
        name: "Thornwall",
        desc: "Raise a bramble of arrows at your feet to fend off the charge.",
        class: Class::Ranger,
        level_req: 26,
        cost: 22,
        resource: Resource::Focus,
        cooldown_ticks: 7,
        effect: AbilityEffect::Ward,
        damage_type: DamageType::Physical,
        magnitude: 40,
        duration: 4,
    },
    Ability {
        id: 507,
        name: "Volley",
        desc: "Rain a quiver's worth of shafts down on the staggering foe.",
        class: Class::Ranger,
        level_req: 31,
        cost: 26,
        resource: Resource::Focus,
        cooldown_ticks: 4,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Physical,
        magnitude: 14,
        duration: 5,
    },
    Ability {
        id: 508,
        name: "Concussive Shot",
        desc: "An arrow to the temple that leaves the enemy reeling and blind.",
        class: Class::Ranger,
        level_req: 37,
        cost: 30,
        resource: Resource::Focus,
        cooldown_ticks: 8,
        effect: AbilityEffect::Stun,
        damage_type: DamageType::Physical,
        magnitude: 16,
        duration: 2,
    },
    Ability {
        id: 509,
        name: "Trueshot Aura",
        desc: "Enter the hunter's stillness where no arrow is ever wasted.",
        class: Class::Ranger,
        level_req: 43,
        cost: 34,
        resource: Resource::Focus,
        cooldown_ticks: 10,
        effect: AbilityEffect::Empower,
        damage_type: DamageType::Physical,
        magnitude: 25,
        duration: 5,
    },
    Ability {
        id: 510,
        name: "Hail of Death",
        desc: "Black out the sky with arrows and let it fall like judgment.",
        class: Class::Ranger,
        level_req: 50,
        cost: 44,
        resource: Resource::Focus,
        cooldown_ticks: 8,
        effect: AbilityEffect::Finisher,
        damage_type: DamageType::Physical,
        magnitude: 84,
        duration: 2,
    },
    // ---- Druid (Spirit) -------------------------------------------------
    Ability {
        id: 800,
        name: "Thorn Lash",
        desc: "Bramble erupts from the ground to rake the foe before you.",
        class: Class::Druid,
        level_req: 1,
        cost: 8,
        resource: Resource::Spirit,
        cooldown_ticks: 1,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Poison,
        magnitude: 12,
        duration: 0,
    },
    Ability {
        id: 801,
        name: "Rejuvenation",
        desc: "Green light settles over you and knits your wounds across the next few moments.",
        class: Class::Druid,
        level_req: 4,
        cost: 14,
        resource: Resource::Spirit,
        cooldown_ticks: 4,
        effect: AbilityEffect::HealOverTime,
        damage_type: DamageType::Holy,
        magnitude: 7,
        duration: 4,
    },
    Ability {
        id: 802,
        name: "Entangling Roots",
        desc: "Roots seize the enemy fast, and for a moment it cannot strike back.",
        class: Class::Druid,
        level_req: 8,
        cost: 16,
        resource: Resource::Spirit,
        cooldown_ticks: 5,
        effect: AbilityEffect::Stun,
        damage_type: DamageType::Poison,
        magnitude: 0,
        duration: 0,
    },
    Ability {
        id: 803,
        name: "Moonfire",
        desc: "A bolt of moonlight that smoulders in the wound, burning on and on.",
        class: Class::Druid,
        level_req: 12,
        cost: 18,
        resource: Resource::Spirit,
        cooldown_ticks: 3,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Arcane,
        magnitude: 10,
        duration: 3,
    },
    Ability {
        id: 804,
        name: "Barkskin",
        desc: "Your skin hardens to living bark, turning aside the next blows to land.",
        class: Class::Druid,
        level_req: 16,
        cost: 20,
        resource: Resource::Spirit,
        cooldown_ticks: 6,
        effect: AbilityEffect::Ward,
        damage_type: DamageType::Physical,
        magnitude: 40,
        duration: 4,
    },
    Ability {
        id: 805,
        name: "Wild Growth",
        desc: "Call the green tide up through your veins and surge back to health at once.",
        class: Class::Druid,
        level_req: 22,
        cost: 28,
        resource: Resource::Spirit,
        cooldown_ticks: 7,
        effect: AbilityEffect::Heal,
        damage_type: DamageType::Holy,
        magnitude: 46,
        duration: 0,
    },
    Ability {
        id: 806,
        name: "Wrath",
        desc: "Starfire gathers in your palm and answers the wild's anger in one stroke.",
        class: Class::Druid,
        level_req: 28,
        cost: 26,
        resource: Resource::Spirit,
        cooldown_ticks: 2,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Arcane,
        magnitude: 30,
        duration: 0,
    },
    Ability {
        id: 807,
        name: "Hurricane",
        desc: "A lashing storm of wind and frost grinds the foe down over long moments.",
        class: Class::Druid,
        level_req: 36,
        cost: 32,
        resource: Resource::Spirit,
        cooldown_ticks: 6,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Frost,
        magnitude: 16,
        duration: 4,
    },
    Ability {
        id: 808,
        name: "Force of Nature",
        desc: "The land itself rises against your enemy - and you draw fresh strength from it.",
        class: Class::Druid,
        level_req: 50,
        cost: 44,
        resource: Resource::Spirit,
        cooldown_ticks: 8,
        effect: AbilityEffect::Finisher,
        damage_type: DamageType::Poison,
        magnitude: 80,
        duration: 2,
    },
    // ---- Necromancer (Souls) --------------------------------------------
    Ability {
        id: 900,
        name: "Shadow Bolt",
        desc: "A dart of cold shadow that drinks the warmth from whatever it strikes.",
        class: Class::Necromancer,
        level_req: 1,
        cost: 8,
        resource: Resource::Souls,
        cooldown_ticks: 1,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Shadow,
        magnitude: 13,
        duration: 0,
    },
    Ability {
        id: 901,
        name: "Corrupt",
        desc: "Rot takes root in the foe, eating away at it long after the spell is cast.",
        class: Class::Necromancer,
        level_req: 4,
        cost: 14,
        resource: Resource::Souls,
        cooldown_ticks: 3,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Shadow,
        magnitude: 9,
        duration: 4,
    },
    Ability {
        id: 902,
        name: "Bone Shield",
        desc: "A cage of risen bone orbits you and shatters the next blows aimed your way.",
        class: Class::Necromancer,
        level_req: 8,
        cost: 16,
        resource: Resource::Souls,
        cooldown_ticks: 6,
        effect: AbilityEffect::Ward,
        damage_type: DamageType::Shadow,
        magnitude: 38,
        duration: 4,
    },
    Ability {
        id: 903,
        name: "Consume Soul",
        desc: "Tear the lingering life from the air around you and pour it into your own frame.",
        class: Class::Necromancer,
        level_req: 12,
        cost: 22,
        resource: Resource::Souls,
        cooldown_ticks: 6,
        effect: AbilityEffect::Heal,
        damage_type: DamageType::Shadow,
        magnitude: 50,
        duration: 0,
    },
    Ability {
        id: 904,
        name: "Curse of Weakness",
        desc: "A whispered hex that locks the enemy's limbs and steals its next strike.",
        class: Class::Necromancer,
        level_req: 16,
        cost: 18,
        resource: Resource::Souls,
        cooldown_ticks: 5,
        effect: AbilityEffect::Stun,
        damage_type: DamageType::Shadow,
        magnitude: 0,
        duration: 0,
    },
    Ability {
        id: 905,
        name: "Wither",
        desc: "Flesh greys and sloughs as a deep decay gnaws the foe from within.",
        class: Class::Necromancer,
        level_req: 22,
        cost: 26,
        resource: Resource::Souls,
        cooldown_ticks: 5,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Shadow,
        magnitude: 15,
        duration: 5,
    },
    Ability {
        id: 906,
        name: "Dark Empowerment",
        desc: "Draw on the gathered dead to sharpen every spell you cast for a while.",
        class: Class::Necromancer,
        level_req: 28,
        cost: 24,
        resource: Resource::Souls,
        cooldown_ticks: 7,
        effect: AbilityEffect::Empower,
        damage_type: DamageType::Shadow,
        magnitude: 18,
        duration: 4,
    },
    Ability {
        id: 907,
        name: "Death Coil",
        desc: "A writhing rope of death-magic that lashes out and crushes the life from a foe.",
        class: Class::Necromancer,
        level_req: 36,
        cost: 30,
        resource: Resource::Souls,
        cooldown_ticks: 3,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Shadow,
        magnitude: 34,
        duration: 0,
    },
    Ability {
        id: 908,
        name: "Soul Reaping",
        desc: "Reach into the foe and tear the soul loose entire - and feel yourself the stronger.",
        class: Class::Necromancer,
        level_req: 50,
        cost: 44,
        resource: Resource::Souls,
        cooldown_ticks: 8,
        effect: AbilityEffect::Finisher,
        damage_type: DamageType::Shadow,
        magnitude: 85,
        duration: 2,
    },
    // ---- Bard (Tempo) ---------------------------------------------------
    Ability {
        id: 1000,
        name: "Dissonant Chord",
        desc: "A jarring note that rattles teeth and breaks the foe's concentration.",
        class: Class::Bard,
        level_req: 1,
        cost: 8,
        resource: Resource::Tempo,
        cooldown_ticks: 1,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Arcane,
        magnitude: 12,
        duration: 0,
    },
    Ability {
        id: 1001,
        name: "Healing Refrain",
        desc: "A gentle, recurring melody that mends you across the next few moments.",
        class: Class::Bard,
        level_req: 4,
        cost: 14,
        resource: Resource::Tempo,
        cooldown_ticks: 4,
        effect: AbilityEffect::HealOverTime,
        damage_type: DamageType::Holy,
        magnitude: 7,
        duration: 4,
    },
    Ability {
        id: 1002,
        name: "Soothing Melody",
        desc: "A swelling chord of comfort that closes wounds all at once.",
        class: Class::Bard,
        level_req: 8,
        cost: 20,
        resource: Resource::Tempo,
        cooldown_ticks: 6,
        effect: AbilityEffect::Heal,
        damage_type: DamageType::Holy,
        magnitude: 42,
        duration: 0,
    },
    Ability {
        id: 1003,
        name: "Cacophony",
        desc: "An ugly, grinding drone that gnaws at the enemy long after the verse ends.",
        class: Class::Bard,
        level_req: 12,
        cost: 18,
        resource: Resource::Tempo,
        cooldown_ticks: 3,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Arcane,
        magnitude: 10,
        duration: 3,
    },
    Ability {
        id: 1004,
        name: "Anthem of War",
        desc: "A rousing march that lends your strikes uncommon force for a while.",
        class: Class::Bard,
        level_req: 16,
        cost: 22,
        resource: Resource::Tempo,
        cooldown_ticks: 7,
        effect: AbilityEffect::Empower,
        damage_type: DamageType::Arcane,
        magnitude: 14,
        duration: 4,
    },
    Ability {
        id: 1005,
        name: "Shrieking Note",
        desc: "A note pitched to shatter resolve - the foe freezes, unable to answer.",
        class: Class::Bard,
        level_req: 22,
        cost: 18,
        resource: Resource::Tempo,
        cooldown_ticks: 5,
        effect: AbilityEffect::Stun,
        damage_type: DamageType::Arcane,
        magnitude: 0,
        duration: 0,
    },
    Ability {
        id: 1006,
        name: "Crescendo",
        desc: "The song peaks in a wall of sound that slams into your enemy at once.",
        class: Class::Bard,
        level_req: 28,
        cost: 26,
        resource: Resource::Tempo,
        cooldown_ticks: 2,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Arcane,
        magnitude: 30,
        duration: 0,
    },
    Ability {
        id: 1007,
        name: "Ballad of Steel",
        desc: "A steadying refrain that wraps you in a shimmer of protective sound.",
        class: Class::Bard,
        level_req: 36,
        cost: 30,
        resource: Resource::Tempo,
        cooldown_ticks: 6,
        effect: AbilityEffect::Ward,
        damage_type: DamageType::Physical,
        magnitude: 40,
        duration: 4,
    },
    Ability {
        id: 1008,
        name: "Finale",
        desc: "The last, devastating chord of the performance - bring the house down on them.",
        class: Class::Bard,
        level_req: 50,
        cost: 44,
        resource: Resource::Tempo,
        cooldown_ticks: 8,
        effect: AbilityEffect::Finisher,
        damage_type: DamageType::Arcane,
        magnitude: 80,
        duration: 2,
    },
    // ---- Monk (Ki) ------------------------------------------------------
    Ability {
        id: 1100,
        name: "Jab",
        desc: "A crisp, snapping blow delivered before the eye can follow it.",
        class: Class::Monk,
        level_req: 1,
        cost: 8,
        resource: Resource::Ki,
        cooldown_ticks: 1,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Physical,
        magnitude: 12,
        duration: 0,
    },
    Ability {
        id: 1101,
        name: "Flurry of Blows",
        desc: "A blur of fists that lands a dozen strikes in the space of one.",
        class: Class::Monk,
        level_req: 4,
        cost: 12,
        resource: Resource::Ki,
        cooldown_ticks: 1,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Physical,
        magnitude: 17,
        duration: 0,
    },
    Ability {
        id: 1102,
        name: "Stunning Strike",
        desc: "A precise blow to a nerve cluster that drops the foe's guard entirely.",
        class: Class::Monk,
        level_req: 8,
        cost: 16,
        resource: Resource::Ki,
        cooldown_ticks: 5,
        effect: AbilityEffect::Stun,
        damage_type: DamageType::Physical,
        magnitude: 0,
        duration: 0,
    },
    Ability {
        id: 1103,
        name: "Mending Ki",
        desc: "Turn your breath inward and knit your own wounds with focused will.",
        class: Class::Monk,
        level_req: 12,
        cost: 20,
        resource: Resource::Ki,
        cooldown_ticks: 6,
        effect: AbilityEffect::Heal,
        damage_type: DamageType::Holy,
        magnitude: 38,
        duration: 0,
    },
    Ability {
        id: 1104,
        name: "Quivering Palm",
        desc: "A touch that sets a fatal vibration humming in the body, growing worse by the moment.",
        class: Class::Monk,
        level_req: 16,
        cost: 22,
        resource: Resource::Ki,
        cooldown_ticks: 4,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Physical,
        magnitude: 12,
        duration: 4,
    },
    Ability {
        id: 1105,
        name: "Diamond Soul",
        desc: "Still your mind until your skin turns blows the way a stone turns rain.",
        class: Class::Monk,
        level_req: 22,
        cost: 24,
        resource: Resource::Ki,
        cooldown_ticks: 6,
        effect: AbilityEffect::Ward,
        damage_type: DamageType::Physical,
        magnitude: 44,
        duration: 4,
    },
    Ability {
        id: 1106,
        name: "Roundhouse",
        desc: "A sweeping kick that lands with the weight of your whole spinning frame.",
        class: Class::Monk,
        level_req: 28,
        cost: 26,
        resource: Resource::Ki,
        cooldown_ticks: 2,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Physical,
        magnitude: 31,
        duration: 0,
    },
    Ability {
        id: 1107,
        name: "Serenity",
        desc: "A breath of perfect calm that briefly lends terrible force to every strike.",
        class: Class::Monk,
        level_req: 36,
        cost: 28,
        resource: Resource::Ki,
        cooldown_ticks: 7,
        effect: AbilityEffect::Empower,
        damage_type: DamageType::Physical,
        magnitude: 22,
        duration: 4,
    },
    Ability {
        id: 1108,
        name: "Touch of Death",
        desc: "The technique a Monk trains a lifetime to never need - and never miss.",
        class: Class::Monk,
        level_req: 50,
        cost: 44,
        resource: Resource::Ki,
        cooldown_ticks: 8,
        effect: AbilityEffect::Finisher,
        damage_type: DamageType::Physical,
        magnitude: 84,
        duration: 2,
    },
    // ---- Paladin (Mana) -------------------------------------------------
    Ability {
        id: 1200,
        name: "Smite",
        desc: "Call down a bolt of judgment that sears the wicked where they stand.",
        class: Class::Paladin,
        level_req: 1,
        cost: 8,
        resource: Resource::Mana,
        cooldown_ticks: 1,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Holy,
        magnitude: 13,
        duration: 0,
    },
    Ability {
        id: 1201,
        name: "Lay on Hands",
        desc: "Press a glowing palm to your wounds and let the Dawn close them.",
        class: Class::Paladin,
        level_req: 4,
        cost: 18,
        resource: Resource::Mana,
        cooldown_ticks: 6,
        effect: AbilityEffect::Heal,
        damage_type: DamageType::Holy,
        magnitude: 44,
        duration: 0,
    },
    Ability {
        id: 1202,
        name: "Consecration",
        desc: "Hallow the ground beneath the foe so it burns the unrighteous over time.",
        class: Class::Paladin,
        level_req: 8,
        cost: 16,
        resource: Resource::Mana,
        cooldown_ticks: 4,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Holy,
        magnitude: 10,
        duration: 4,
    },
    Ability {
        id: 1203,
        name: "Divine Shield",
        desc: "A barrier of pure faith that turns aside the next blows to fall on you.",
        class: Class::Paladin,
        level_req: 12,
        cost: 20,
        resource: Resource::Mana,
        cooldown_ticks: 6,
        effect: AbilityEffect::Ward,
        damage_type: DamageType::Holy,
        magnitude: 45,
        duration: 4,
    },
    Ability {
        id: 1204,
        name: "Holy Strike",
        desc: "A blade wreathed in blessed light that bites far deeper than steel should.",
        class: Class::Paladin,
        level_req: 16,
        cost: 18,
        resource: Resource::Mana,
        cooldown_ticks: 2,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Holy,
        magnitude: 24,
        duration: 0,
    },
    Ability {
        id: 1205,
        name: "Hammer of Justice",
        desc: "A hurled warhammer of light that pins the foe and halts its next strike.",
        class: Class::Paladin,
        level_req: 22,
        cost: 20,
        resource: Resource::Mana,
        cooldown_ticks: 5,
        effect: AbilityEffect::Stun,
        damage_type: DamageType::Holy,
        magnitude: 0,
        duration: 0,
    },
    Ability {
        id: 1206,
        name: "Blessing of Might",
        desc: "Speak a blessing over your arm that lends your blows holy force for a time.",
        class: Class::Paladin,
        level_req: 28,
        cost: 24,
        resource: Resource::Mana,
        cooldown_ticks: 7,
        effect: AbilityEffect::Empower,
        damage_type: DamageType::Holy,
        magnitude: 18,
        duration: 4,
    },
    Ability {
        id: 1207,
        name: "Sacred Word",
        desc: "A whispered prayer that knits your flesh steadily over the moments to come.",
        class: Class::Paladin,
        level_req: 36,
        cost: 22,
        resource: Resource::Mana,
        cooldown_ticks: 5,
        effect: AbilityEffect::HealOverTime,
        damage_type: DamageType::Holy,
        magnitude: 9,
        duration: 4,
    },
    Ability {
        id: 1208,
        name: "Avenging Wrath",
        desc: "Loose the full fury of the Dawn in one cleansing, ruinous stroke.",
        class: Class::Paladin,
        level_req: 50,
        cost: 44,
        resource: Resource::Mana,
        cooldown_ticks: 8,
        effect: AbilityEffect::Finisher,
        damage_type: DamageType::Holy,
        magnitude: 82,
        duration: 2,
    },
    // ---- Warlock (Mana) -------------------------------------------------
    Ability {
        id: 1300,
        name: "Chaos Bolt",
        desc: "A roiling ball of raw pact-fire that strikes with malicious certainty.",
        class: Class::Warlock,
        level_req: 1,
        cost: 8,
        resource: Resource::Mana,
        cooldown_ticks: 1,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Shadow,
        magnitude: 13,
        duration: 0,
    },
    Ability {
        id: 1301,
        name: "Curse of Agony",
        desc: "A creeping hex that wracks the foe with worsening pain.",
        class: Class::Warlock,
        level_req: 4,
        cost: 14,
        resource: Resource::Mana,
        cooldown_ticks: 3,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Shadow,
        magnitude: 9,
        duration: 4,
    },
    Ability {
        id: 1302,
        name: "Demon Skin",
        desc: "Toughen your hide with a sheath of bargained shadow.",
        class: Class::Warlock,
        level_req: 8,
        cost: 16,
        resource: Resource::Mana,
        cooldown_ticks: 6,
        effect: AbilityEffect::Ward,
        damage_type: DamageType::Shadow,
        magnitude: 38,
        duration: 4,
    },
    Ability {
        id: 1303,
        name: "Soul Leech",
        desc: "Siphon the failing warmth of the world around you back into yourself.",
        class: Class::Warlock,
        level_req: 12,
        cost: 22,
        resource: Resource::Mana,
        cooldown_ticks: 6,
        effect: AbilityEffect::Heal,
        damage_type: DamageType::Shadow,
        magnitude: 46,
        duration: 0,
    },
    Ability {
        id: 1304,
        name: "Searing Pact",
        desc: "Call up flame born of your bargain and hurl it scorching at the foe.",
        class: Class::Warlock,
        level_req: 16,
        cost: 18,
        resource: Resource::Mana,
        cooldown_ticks: 2,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Fire,
        magnitude: 24,
        duration: 0,
    },
    Ability {
        id: 1305,
        name: "Fear",
        desc: "Pour raw dread into the enemy's mind until it cannot bring itself to strike.",
        class: Class::Warlock,
        level_req: 22,
        cost: 18,
        resource: Resource::Mana,
        cooldown_ticks: 5,
        effect: AbilityEffect::Stun,
        damage_type: DamageType::Shadow,
        magnitude: 0,
        duration: 0,
    },
    Ability {
        id: 1306,
        name: "Dark Bargain",
        desc: "Spend a little of yourself to the pact and sharpen every spell for a while.",
        class: Class::Warlock,
        level_req: 28,
        cost: 24,
        resource: Resource::Mana,
        cooldown_ticks: 7,
        effect: AbilityEffect::Empower,
        damage_type: DamageType::Shadow,
        magnitude: 18,
        duration: 4,
    },
    Ability {
        id: 1307,
        name: "Wracking Pain",
        desc: "A deeper curse that tears at the foe from the inside for long, ugly moments.",
        class: Class::Warlock,
        level_req: 36,
        cost: 28,
        resource: Resource::Mana,
        cooldown_ticks: 5,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Shadow,
        magnitude: 15,
        duration: 5,
    },
    Ability {
        id: 1308,
        name: "Cataclysm",
        desc: "Call in the full price of your pact at once and bring the dark down on them.",
        class: Class::Warlock,
        level_req: 50,
        cost: 44,
        resource: Resource::Mana,
        cooldown_ticks: 8,
        effect: AbilityEffect::Finisher,
        damage_type: DamageType::Shadow,
        magnitude: 85,
        duration: 2,
    },
    // ---- Berserker (Rage) -----------------------------------------------
    Ability {
        id: 1400,
        name: "Reckless Swing",
        desc: "A wild, committed blow that trades all defense for raw damage.",
        class: Class::Berserker,
        level_req: 1,
        cost: 8,
        resource: Resource::Rage,
        cooldown_ticks: 1,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Physical,
        magnitude: 14,
        duration: 0,
    },
    Ability {
        id: 1401,
        name: "Rampage",
        desc: "Wade in swinging and let the blows come as fast as your arms allow.",
        class: Class::Berserker,
        level_req: 4,
        cost: 12,
        resource: Resource::Rage,
        cooldown_ticks: 1,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Physical,
        magnitude: 17,
        duration: 0,
    },
    Ability {
        id: 1402,
        name: "Intimidating Shout",
        desc: "A roar so savage the foe flinches and loses its next strike.",
        class: Class::Berserker,
        level_req: 8,
        cost: 16,
        resource: Resource::Rage,
        cooldown_ticks: 5,
        effect: AbilityEffect::Stun,
        damage_type: DamageType::Physical,
        magnitude: 0,
        duration: 0,
    },
    Ability {
        id: 1403,
        name: "Second Wind",
        desc: "Spit blood, grin, and drag yourself back from the edge by sheer will.",
        class: Class::Berserker,
        level_req: 12,
        cost: 18,
        resource: Resource::Rage,
        cooldown_ticks: 6,
        effect: AbilityEffect::Heal,
        damage_type: DamageType::Holy,
        magnitude: 36,
        duration: 0,
    },
    Ability {
        id: 1404,
        name: "Crippling Blow",
        desc: "A brutal hit that opens a wound which keeps on bleeding.",
        class: Class::Berserker,
        level_req: 16,
        cost: 20,
        resource: Resource::Rage,
        cooldown_ticks: 4,
        effect: AbilityEffect::DamageOverTime,
        damage_type: DamageType::Physical,
        magnitude: 12,
        duration: 4,
    },
    Ability {
        id: 1405,
        name: "Battle Trance",
        desc: "Sink into the red haze where every swing lands like a falling tree.",
        class: Class::Berserker,
        level_req: 22,
        cost: 22,
        resource: Resource::Rage,
        cooldown_ticks: 7,
        effect: AbilityEffect::Empower,
        damage_type: DamageType::Physical,
        magnitude: 16,
        duration: 4,
    },
    Ability {
        id: 1406,
        name: "Brutal Cleave",
        desc: "A two-handed stroke that splits guard and bone alike.",
        class: Class::Berserker,
        level_req: 28,
        cost: 26,
        resource: Resource::Rage,
        cooldown_ticks: 2,
        effect: AbilityEffect::Strike,
        damage_type: DamageType::Physical,
        magnitude: 32,
        duration: 0,
    },
    Ability {
        id: 1407,
        name: "Last Stand",
        desc: "Plant your feet and refuse to fall, shrugging off the next blows to land.",
        class: Class::Berserker,
        level_req: 36,
        cost: 28,
        resource: Resource::Rage,
        cooldown_ticks: 6,
        effect: AbilityEffect::Ward,
        damage_type: DamageType::Physical,
        magnitude: 44,
        duration: 4,
    },
    Ability {
        id: 1408,
        name: "Undying Rage",
        desc: "Burn every last ember of fury in one ruinous, world-ending swing.",
        class: Class::Berserker,
        level_req: 50,
        cost: 44,
        resource: Resource::Rage,
        cooldown_ticks: 8,
        effect: AbilityEffect::Finisher,
        damage_type: DamageType::Physical,
        magnitude: 88,
        duration: 2,
    },
];

/// Abilities a character of this class has unlocked at this level, lowest level first.
pub fn unlocked_for(class: Class, level: i32) -> Vec<&'static Ability> {
    let mut out: Vec<&'static Ability> = ABILITIES
        .iter()
        .filter(|a| a.class == class && a.level_req <= level)
        .collect();
    out.sort_by_key(|a| a.level_req);
    out
}

/// The ability a class learns exactly at `level`, if any (for level-up messages).
pub fn learned_at(class: Class, level: i32) -> Option<&'static Ability> {
    ABILITIES
        .iter()
        .find(|a| a.class == class && a.level_req == level)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::app::door::lateania::classes::Class;

    #[test]
    fn every_class_has_a_level_one_ability() {
        for class in Class::ALL {
            let early = unlocked_for(class, 1);
            assert!(!early.is_empty(), "{:?} has no level-1 ability", class);
        }
    }

    #[test]
    fn ability_ids_are_unique() {
        let mut ids: Vec<u32> = ABILITIES.iter().map(|a| a.id).collect();
        ids.sort_unstable();
        let n = ids.len();
        ids.dedup();
        assert_eq!(n, ids.len(), "duplicate ability id");
    }

    #[test]
    fn every_class_has_a_capstone_at_fifty() {
        for class in Class::ALL {
            let capstone = ABILITIES
                .iter()
                .any(|a| a.class == class && a.level_req == 50);
            assert!(capstone, "{:?} has no level-50 capstone", class);
        }
    }

    #[test]
    fn unlocks_are_monotonic_with_level() {
        for class in Class::ALL {
            let low = unlocked_for(class, 10).len();
            let high = unlocked_for(class, 50).len();
            assert!(high >= low, "{:?} unlocks should not shrink", class);
            assert!(high >= 8, "{:?} should have a deep kit by 50", class);
        }
    }
}
